### ISSUE TITLE
structure の elementとtitle 

### ISSUE THREAD

**Issue by choru-k** [cookpad/2018-newgrads-engineer-portfolio#2]
現在`portfolio.yml`の`skill_levels`のしたにある`elements`の中に`title`がありますが、`structure.yml`と比べると`element`が方がもっと正しいと思いますが、確認お願いします。
```yml
# before
-  title: C言語
   level: 1
   years: 1
   explanation: |
      授業で習った
```
```yml
# after
-  element: C言語
   level: 1
   years: 1
   explanation: |
      授業で習った
```
